//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LiberPlayer.rc
//
#define IDI_MAIN                        5
#define IDD_WAIT                        9
#define IDR_MAINFRAME                   101
#define IDD_DIALOG1                     102
#define IDR_FDOCHOSTUIHANDLER           103
#define IDB_QUICKTIME                   104
#define IDR_QUICKTIME                   105
#define IDR_RMENU                       112
#define IDR_TRAY                        115
#define IDR_DOWNLOAD_STATUS             116
#define IDS_CONFIRM_REMOVE              117
#define IDS_WARNING                     118
#define IDS_TRAYWND_ERROR               119
#define IDS_ERROR                       120
#define IDS_FATAL                       121
#define IDS_ERROR_LOADING_METATORRENT   122
#define IDS_ERROR_STARTING_DOWNLOAD     123
#define IDS_ERROR_STARTING_PLAYBACK     124
#define IDS_PLAYBACK_ERROR              125
#define IDR_LIBER2PLAYER                126
#define IDR_FHTMLEVENTHANDLER           127
#define IDR_FHTMLEVENTDISPATCHER        128
#define IDI_STATUS                      128
#define IDI_NOT_CONNECTABLE             129
#define IDR_MENU1                       130
#define IDR_CHANNELGUIDE                130
#define IDR_MAINFRAME1                  131
#define IDI_ICON1                       140
#define IDD_DIALOG2                     144
#define IDD_DIALOG3                     147
#define IDD_OPENMTT                     147
#define IDD_STORAGE_CHANGE              148
#define IDB_LOGO                        149
#define IDD_OPENMTT1                    149
#define IDD_LABEL                       151
#define IDD_OPEN_STATION                152
#define IDD_OPENMTT2                    153
#define IDD_MESSAGEBOX                  153
#define IDD_NEW_VERSION                 153
#define IDD_SESSION_STATUS              156
#define IDD_CONF_WIZARD                 157
#define IDD_SAVE_VIDEO                  157
#define IDI_ICON2                       159
#define IDD_DOWNLOAD_STARTED            160
#define IDI_COLLECTION                  161
#define IDB_SAVE                        163
#define IDD_DIALOG4                     166
#define IDD_ADD_FEED                    167
#define IDI_TEST_ICON                   168
#define IDD_PLUGIN_DOWNLOAD             169
#define IDB_UP                          170
#define IDB_DOWN                        171
#define IDI_TESTICON                    172
#define IDI_ICON_PAUSED                 173
#define IDI_ICON3                       176
#define IDI_ICON_QUEUED                 176
#define IDI_ICON_RSS                    177
#define IDI_ICON4                       178
#define IDI_ICON_RSS_AUTO               178
#define IDI_ICON_FINISHED               179
#define IDI_ICON_IN_PROGRESS            180
#define IDI_ICON_ERROR                  181
#define IDI_ICON_QUEUED1                182
#define IDD_COLLECTION_FOLDER           185
#define IDD_REMOVE_VIDEO                187
#define IDR_MENU2                       188
#define IDD_SHARE_MOVIE                 189
#define IDC_SESSION                     1002
#define IDC_FILE_NAME                   1003
#define IDC_BROWSE                      1004
#define IDC_EDIT2                       1005
#define IDC_DESCRIPTION                 1005
#define IDC_PROGRESS1                   1006
#define IDC_MESSAGE                     1007
#define IDC_STOP                        1009
#define IDC_PLAY                        1010
#define IDC_CATEGORY                    1011
#define IDC_TAB_NAME                    1012
#define IDC_DETAIL                      1013
#define IDC_CHECK1                      1014
#define IDC_ALWAYS_STORE                1014
#define IDC_DONT_SHOW_AGAIN             1014
#define IDC_GET_FROM_CHANNEL            1014
#define IDC_AUTO_UPDATE                 1014
#define IDC_DONT_SHOW                   1014
#define IDC_CHECK2                      1015
#define IDC_EDIT1                       1015
#define IDLEAVE                         1016
#define IDC_EDIT3                       1016
#define IDDELETE                        1017
#define IDC_LABEL                       1018
#define IDC_STATION_URL                 1019
#define IDC_PEERS                       1021
#define IDC_VIDEO_NAME                  1022
#define IDC_VIDEO_SIZE                  1023
#define IDC_VIDEO_PARTS                 1024
#define IDC_STORAGE_FOLDER              1026
#define IDC_FREE_SPACE                  1028
#define IDC_FREE_SPACE2                 1029
#define IDC_COUNTRY                     1030
#define IDC_FEED_NAME                   1031
#define IDC_FEED_ADDRESS                1032
#define IDC_DETAILS                     1034
#define IDC_LABEL_NAME                  1035
#define IDC_INVALID_URL                 1036
#define ID_CHANGE_FOLDER                1037
#define IDC_FOLDER                      1038
#define IDC_FILES                       1040
#define IDC_ADD                         1041
#define ID_FILE_EXIT                    40001
#define ID_FILE_PLAY                    40002
#define ID_FILE_OPENVIDEOFILE           40003
#define IDC_PAUSE                       40009
#define ID_BUTTON40010                  40010
#define IDC_VIEWSTATUS                  40011
#define IDC_SLIDER                      40022
#define ID_Menu                         40023
#define ID_Menu40024                    40024
#define IDC_VOLUME                      40025
#define IDC_OPENVIDEO                   40027
#define ID_VIDEO                        40028
#define ID_VIDEO_OPENVIDEO              40029
#define ID_Menu40030                    40030
#define IDC_STATUS                      40034
#define IDC_EXIT                        40036
#define IDC_PAUSE_EXCEPT                40041
#define IDC_REMOVEDOWNLOAD              40043
#define IDC_TSTATUS                     40045
#define IDC_LOAD_METATORRENT            40046
#define IDC_OPEN_METATORRENT            40047
#define IDC_REMOVEANDDISCARD            40049
#define IDC_WEB_WINDOW                  40050
#define IDC_BROWSER_HOME                40054
#define IDC_BROWSER_FORWARD             40055
#define IDC_BROWSER_BACK                40056
#define IDC_TEST                        40058
#define IDC_SETTINGS                    40060
#define ID_TRAY_ANNOUNCE                40061
#define ID_TRAY_LTREANNOUNCE            40062
#define ID_TRAY_PAUSEDOWNLOADS          40063
#define ID_TRAY_OPENPLAYER              40064
#define ID_FILE_EXIT40065               40065
#define ID_FILE_OPENSTATION             40066
#define ID_Menu40067                    40067
#define ID_FILE_SETTINGS                40068
#define ID_VIEW_PLAYER                  40070
#define ID_VIEW_CHANNELGUIDE            40073
#define ID_HELP_ABOUT                   40075
#define ID_VIEW_FULLSCREEN              40076
#define ID_VIEW_MYCOLLECTION            40077
#define ID_HELP_HELP                    40078
#define ID_NETWORK_GLOBALREANNOUNCE     40079
#define ID_Menu40080                    40080
#define ID_TRAY_LOGWINDOW               40081
#define ID_VIEW_VIDEO                   40082
#define ID_ASPECTRATIO_AUTOMATIC        40083
#define ID_ASPECTRATIO_4                40084
#define ID_ASPECTRATIO_16               40085
#define ID_Menu40086                    40086
#define ID_UPLOAD_UPLOADCONTENT         40087
#define ID_TRAY_FEEDBACK                40088
#define ID_VIEW_QUICKBAR                40089
#define ID_TRAY_TEST                    40091
#define ID_CHANNELGUIDE_COPY            40092
#define ID_CHANNELGUIDE_PASTE           40093
#define ID_CHANNELGUIDE_HOME            40094
#define ID_FILE_OPENSTATION40095        40095
#define ID_MAIN_FILE                    40096
#define ID_MAIN_VIEW                    40097
#define ID_MAIN_HELP                    40098
#define ID_FILE_SETTINGS40099           40099
#define ID_VIEW_SESSIONSTATUS           40100
#define ID_FILE_SELECTSERVER            40102
#define ID_VIEW_SUBSCRIPTIONS           40103
#define ID_Menu40104                    40104
#define ID_Menu40105                    40105
#define ID_CHANGE_COLLECTION            40106
#define ID_PLAYER_FULLSCREEN            40107
#define ID_PLAYER_CHANGESUBTITLE        40108
#define ID_PLAYER_CYCLEASPECTRATIO      40109
#define ID_FILE_SHARE                   40110

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        190
#define _APS_NEXT_COMMAND_VALUE         40111
#define _APS_NEXT_CONTROL_VALUE         1042
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
